### ISSUE TITLE
fix!: Fix a TimeRange off-by-one bug in nanosecond calculation

### ISSUE THREAD

**Issue by deephaven-internal** [deephaven/deephaven-docs-community#302]
_This issue was auto-generated_

PR: https://github.com/deephaven/deephaven-core/pull/5648
Author: chipkent

## Original PR Body

Fix a TimeRange off-by-one bug in nanosecond calculation.

Resolves #5646 

BREAKING CHANGE: The length of a business day was being incorrectly computed by 1 ns.  To keep the business day length the same for existing calendars, the close of a business period has been changed from inclusive to exclusive.  This default behavior can be overridden by using `<includeClose>true</includeClose>` when specifying time ranges.  This will include the closing time for the range and will result in a business period that is 1 ns longer.  Business calendars using the legacy format must be upgraded to the current format to use `<includeClose>true</includeClose>`.

**Comment by alexpeters1208** [comment]
It's not obvious that anything needs to change [in the Pydocs](https://deephaven.io/core/pydoc/code/deephaven.calendar.html#module-deephaven.calendar), since business day length is not explicitly mentioned anywhere.

It is also not obvious that anything needs to change [in the Calendars guide](https://deephaven.io/core/docs/how-to-guides/business-calendar/).

However, something may need to change [here](https://deephaven.io/core/javadoc/io/deephaven/time/calendar/BusinessCalendar.html). In particular, some methods like [`businessDates`](https://deephaven.io/core/javadoc/io/deephaven/time/calendar/BusinessCalendar.html#businessDates(java.time.Instant,java.time.Instant,boolean,boolean)) have parameter names `startInclusive` and `endInclusive`. Have the "defaults" on the second parameter implicitly changed?
Many other methods like [`businessDates`](https://deephaven.io/core/javadoc/io/deephaven/time/calendar/BusinessCalendar.html#businessDates(java.time.LocalDate,java.time.LocalDate)) have `start` and `end` parameters, both called "inclusive". Is it now the case that `start` is inclusive and `end` is exclusive across the board?

**Comment by chipkent** [comment]
The `BusinessCalendar` methods you mention do not need to change.  They do exactly what they say.  They have not changed.

The bug was in how `TimeRange` was being computed.  Off-by-one.  See https://github.com/deephaven/deephaven-core/pull/5648/files#diff-54ece697448ad466b3a5b659e70da856bbe21c18973c787e62c2506ba8b68fc5.

The only other change of note -- which may require documentation --, is some additional configurability in the calendar XML files.  Also see https://github.com/deephaven/deephaven-core/pull/5648/files#diff-54ece697448ad466b3a5b659e70da856bbe21c18973c787e62c2506ba8b68fc5.

**Comment by alexpeters1208** [comment]
This is the only real place I can find config details on these XML files: https://deephaven.io/core/javadoc/io/deephaven/time/calendar/BusinessCalendarXMLParser.html
The currently released Javadocs do not include this change, but Chip included the Javadoc change in his PR, and it will be in the next release.

The other "docs" is this example, linked to from the Calendars guide: https://github.com/deephaven/deephaven-core/blob/main/props/configs/src/main/resources/calendar/UTC.calendar
It is already updated to include the new config stuff.

I can't find anywhere else where we document config details. The calendars guide just points to the examples in GH, and if you're looking, you can find the Javadoc. If we want docsite docs for these config details, that is a bigger PR than this ticket warrants.

**Comment by chipkent** [comment]
Looks like there is no work to do for this PR.
