### ISSUE TITLE
Working with Deephaven tables > Data types 

### ISSUE THREAD

**Issue by margaretkennedy** [deephaven/deephaven-docs-community#50]
This page should be an edit or overhaul of our existing guide on data types: https://deephaven.io/core/docs/conceptual/data-types/

@nbauernfeind  to review

This is part of the top-level Working with Deephaven tables section, with the following sub-sections:
* Data types
* Deephaven queries 
  |   | The table API
  |   | Deephaven "query strings"
  |   | Work with formulas & filters
  |   | Built-in functions
  |   | User-defined functions
  |   | Numba and Deephaven queries
  |   | Work with strings
  |   | Work with time
  |   | Work with calendars
  |   | Use Python objects in queries

Two open issues may be relevant:

primitives: https://github.com/deephaven/deephaven.io/issues/1346 and https://github.com/deephaven/deephaven-core/pull/2288

**Comment by jjbrosnan** [comment]
I just read the entire guide, and found no issues with it. The material is still relevant with the current API, and the doc is structured well. Rewriting it is unnecessary.

We could turn this ticket into `Create the equivalent Groovy guide`, but there really isn't one, since Groovy ~= Java when it comes to data types.

I'll defer to @margaretkennedy  to close this ticket or change it to `Add a Groovy data types guide`, though I don't think it's necessary.
